<a href="https://colab.research.google.com/github/AnannyaSagar/Python_Problems/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

Convert list into a one-dimensional array 

In [3]:
OL = [12.23, 13.32, 100, 36.32]

arr = np.array(OL)
arr

array([ 12.23,  13.32, 100.  ,  36.32])

Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [6]:
np.arange(2,11).reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

Write a NumPy program to create a null vector of size 10 and update sixth value to 11.

In [8]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
a[6] = 11

In [10]:
a

array([ 0.,  0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.])

Write a NumPy program to create an array with values ranging from 12 to 38

In [11]:
b = np.arange(12,38)
b

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

Reverse the array

In [12]:
b[::-1]

array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])

In [13]:
c = np.asfarray(b)
c

array([12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.,
       25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37.])

In [15]:
d = np.ones((5,5))
d

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
d[1:-1,1:-1] = 0
d

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
y = np.zeros((8,8))
y

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
y[1::2,::2] =1

In [21]:
y[::2, 1::2] = 1

In [22]:
y

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [24]:
k = [1,2,3,4,5,6]
l = ([2,4,6],[1,3,5])

k1 = np.array(k)
l1 = np.array(l)

print(k1)

print(l1)

[1 2 3 4 5 6]
[[2 4 6]
 [1 3 5]]


In [33]:
p = np.array([10,20,30])

l = np.append(p,[[40, 50, 60], [70, 80, 90]])

l

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [39]:
x = np.empty((3,4))
y = np.full((3,3),8)

In [40]:
x

array([[4.05330191e-316, 6.79038653e-313, 2.37663529e-312,
        2.16443571e-312],
       [2.29175545e-312, 8.48798317e-313, 1.08221785e-312,
        1.08221785e-312],
       [9.33678148e-313, 8.70018275e-313, 3.99910963e+252,
        1.46030983e-319]])

In [41]:
y

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])